name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t cryptopals-set01 -f set01/Dockerfile set01
    - name: Run tests
      run: docker run -t cryptopals-set01
